---
abstract: 'RT-Action-NotifyPagerDuty Extension'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Action-NotifyPagerDuty
no_index:
  directory:
    - inc
requires:
  perl: 5.10.1
resources:
  repository: https://github.com/catalyst-cloud/RT-Extension-Action-NotifyPagerDuty
version: '0.02'
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.4.0
